"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ModeToggle";
import Image from "next/image";
import Shantanu2 from "../../public/Shantanu.jpeg";
import { FaInstagram, FaLinkedin, FaMailBulk } from "react-icons/fa";
import { CgMail } from "react-icons/cg";
import { Separator } from "@/components/ui/separator";
import ButtonShapeTabs from "@/components/syntaxUI/tabs";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="container relative mx-auto flex flex-col py-12 max-w-[1000px]">
            <nav className="flex justify-between mb-3">
              <Image
                src="/Dhaatri.jpeg"
                alt="Dhaatri"
                width={100}
                height={100}
                style={{
                  borderRadius: "100%",
                }}
              />
              <ModeToggle />
            </nav>
            <h1 className="font-[apple-font-medium] text-2xl">
              Dhaatri Prasanna
            </h1>
            <h2 className="text-sm text-gray-500 mt-1 italic">
              ML Engineer | Teacher{" "}
            </h2>

            <div className="flex gap-4 py-4">
              {/* <a
                href="/Shantanu_Kudva_CV_2024 (2).pdf"
                target="_blank"
                className="text-2xl cursor-pointer"
              >
                <BsPersonFill />
              </a> */}
              <a
                href="https://www.linkedin.com/in/dhaatri-rao-27a2591b4/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-2xl cursor-pointer"
              >
                <FaLinkedin />
              </a>
              <a
                href="https://instagram.com/dhaatri_rao/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-2xl cursor-pointer"
              >
                <FaInstagram />
              </a>
              <a
                href="mailto:dhaatriiprasanna@gmail.com"
                className="text-2xl cursor-pointer"
              >
                <CgMail />
              </a>
            </div>

            <Separator className="mx-2 my-4" />

            <div className="mt-3">
              <ButtonShapeTabs />
            </div>
            {children}
          </div>
          <footer className="mb-10">
            <div className="text-sm flex justify-center items-center">
              <p className="leading-5 text-gray-700 font-[apple-font-regular]">
                &copy; {new Date().getFullYear()} - Made by Shantanu Kudva.
              </p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
